# Generated by Django 4.0.4 on 2022-05-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskTitle', models.CharField(max_length=50)),
                ('TaskDescriptions', models.CharField(max_length=500)),
            ],
        ),
    ]
